services:
  db:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: TEST_DB
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    # not to expose ports outside
    # ports:
    #   - "3306:3306"
    expose:
      - 3306

  backend:
    container_name: backend
    build: ./minimal-backend
    restart: always
    depends_on:
      db :
        condition: service_healthy
    environment:
      APP_PORT: 4000
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: rootpassword
      DATABASE_NAME: TEST_DB
      NODE_ENV: development
    # ports:
    # - "4000:4000"
    expose:
      - 4000
    command: bash -c "
      npx sequelize-cli db:create &&
      npx sequelize-cli db:migrate &&
      npx sequelize-cli db:seed:all &&
      npm start "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 5s
      timeout: 5s
      retries: 3

  frontend:
    container_name: frontend
    build: ./minimal-frontend
    # ports:
    # - "3000:3000"
    expose:
      - 3000
    command: bash -c "npm start "

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
      - ./nginx:/etc/nginx/conf.d/
